import Head from 'next/head'
import Navbar from "../components/Navbar";
import HomePage from "./homePage";
import Services from "./services";
import Works from "./works";
import Redes from "./redes";
import Footer from "../components/Footer";

export default function Home() {
	return (
		<div>
        <Head>
              <title>Portfólio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/icone.png" />
        </Head>
			<Navbar />
                  <HomePage />
                  <Services />
                  <Works />
                  <Redes />
                  <Footer />
		</div>
	);
}
